"""create remaining core tables

Revision ID: d375be3e9a1b
Revises: 64c493fdd04b
Create Date: 2026-09-22 21:13:06.790929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd375be3e9a1b'
down_revision: Union[str, Sequence[str], None] = '64c493fdd04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('work_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_therapists_name'), 'therapists', ['name'], unique=False)
    op.create_index(op.f('ix_therapists_specialty'), 'therapists', ['specialty'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(length=120), nullable=True),
    sa.Column('sessions_total', sa.Integer(), nullable=False),
    sa.Column('sessions_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age >= 0 AND age <= 120', name='ck_patients_age_range'),
    sa.CheckConstraint('sessions_total >= 0', name='ck_patients_sessions_total_nonneg'),
    sa.CheckConstraint('sessions_used <= sessions_total', name='ck_patients_sessions_used_le_total'),
    sa.CheckConstraint('sessions_used >= 0', name='ck_patients_sessions_used_nonneg'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_index(op.f('ix_patients_therapist_id'), 'patients', ['therapist_id'], unique=False)
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_off', sa.Boolean(), nullable=False),
    sa.Column('custom_start', sa.Time(), nullable=True),
    sa.Column('custom_end', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('therapist_id', 'date', name='uq_schedule_exception_therapist_date')
    )
    op.create_index(op.f('ix_schedule_exceptions_date'), 'schedule_exceptions', ['date'], unique=False)
    op.create_index(op.f('ix_schedule_exceptions_therapist_id'), 'schedule_exceptions', ['therapist_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('payment_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_appointments_end_after_start'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('therapist_id', 'date', 'start_time', name='uq_appointments_therapist_date_start')
    )
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_index('ix_appointments_patient_date', 'appointments', ['patient_id', 'date'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_therapist_date', 'appointments', ['therapist_id', 'date'], unique=False)
    op.create_index(op.f('ix_appointments_therapist_id'), 'appointments', ['therapist_id'], unique=False)
    op.create_table('report_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_files_patient_id'), 'report_files', ['patient_id'], unique=False)
    op.create_index(op.f('ix_report_files_uploaded_at'), 'report_files', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_report_files_uploaded_by'), 'report_files', ['uploaded_by'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('note_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('pain_location', sa.String(length=120), nullable=True),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('rom', sa.Text(), nullable=True),
    sa.Column('rom_score', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('strength_score', sa.Integer(), nullable=True),
    sa.Column('special_tests', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('exercises', sa.Text(), nullable=True),
    sa.Column('patient_response', sa.Text(), nullable=True),
    sa.Column('hep', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('therapist_notes', sa.Text(), nullable=True),
    sa.Column('milestone', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pain_score IS NULL OR (pain_score >= 0 AND pain_score <= 10)', name='ck_clinical_notes_pain_score_range'),
    sa.CheckConstraint('rom_score IS NULL OR (rom_score >= 0 AND rom_score <= 100)', name='ck_clinical_notes_rom_score_range'),
    sa.CheckConstraint('strength_score IS NULL OR (strength_score >= 0 AND strength_score <= 5)', name='ck_clinical_notes_strength_score_range'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_appointment_id'), 'clinical_notes', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_note_date'), 'clinical_notes', ['note_date'], unique=False)
    op.create_index(op.f('ix_clinical_notes_patient_id'), 'clinical_notes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_therapist_id'), 'clinical_notes', ['therapist_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_invoices_amount_nonneg'),
    sa.CheckConstraint('discount <= amount', name='ck_invoices_discount_le_amount'),
    sa.CheckConstraint('discount >= 0', name='ck_invoices_discount_nonneg'),
    sa.CheckConstraint('paid_amount >= 0', name='ck_invoices_paid_amount_nonneg'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_appointment_id'), 'invoices', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_invoices_date'), 'invoices', ['date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_appointment_id', sa.Integer(), nullable=True),
    sa.Column('related_invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_appointment_id'), 'notifications', ['related_appointment_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_invoice_id'), 'notifications', ['related_invoice_id'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('method_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_refund = true AND amount < 0) OR (is_refund = false AND amount > 0)', name='ck_payments_refund_sign_consistency'),
    sa.CheckConstraint('amount != 0', name='ck_payments_amount_nonzero'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_created_by'), 'payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_is_refund'), 'payments', ['is_refund'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_is_refund'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_by'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_invoice_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_appointment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_appointment_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_clinical_notes_therapist_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_patient_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_note_date'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_appointment_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_report_files_uploaded_by'), table_name='report_files')
    op.drop_index(op.f('ix_report_files_uploaded_at'), table_name='report_files')
    op.drop_index(op.f('ix_report_files_patient_id'), table_name='report_files')
    op.drop_table('report_files')
    op.drop_index(op.f('ix_appointments_therapist_id'), table_name='appointments')
    op.drop_index('ix_appointments_therapist_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index('ix_appointments_patient_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_schedule_exceptions_therapist_id'), table_name='schedule_exceptions')
    op.drop_index(op.f('ix_schedule_exceptions_date'), table_name='schedule_exceptions')
    op.drop_table('schedule_exceptions')
    op.drop_index(op.f('ix_patients_therapist_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_therapists_specialty'), table_name='therapists')
    op.drop_index(op.f('ix_therapists_name'), table_name='therapists')
    op.drop_table('therapists')
    # ### end Alembic commands ###
